region             = "eu-west-1"
instance_type      = "t2.micro"
instance_key       = "ssh_test"
vpc_cidr           = "10.0.0.0/16"
creds_path         = "~/.aws/"
creds_file         = "credentials"
private_key_path   = "./ssh_test.pem"
