apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: argocd
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
    #name: kind
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.1.0
    helm:
      valueFiles:
      - https://github.com/CarlosBarroso/terraform/gcloud/infrastructura/jenkins/values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true