apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
     stack: deck
   name: spin-deck-ui
spec:
  type: LoadBalancer
ports:
  - name: http
    port: 9000
    protocol: TCP
selector:
    cluster: "spin-deck"